// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    name: "User",
    email: "user@nextmail.com",
    password: "123456",
  },
  {
    name: "Jesse",
    email: "jesse@fakedomain.com",
    password: "123456",
  },
  {
    name: "Alexia",
    email: "alexia@fakedomain.com",
    password: "123456",
  },
];

const discs = [
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked up",
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    date: "2024-12-16",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked up",
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
  },
];

const trends = [
  { month: "Jan", found: 20, returned: 18 },
  { month: "Feb", found: 21, returned: 20 },
  { month: "Mar", found: 22, returned: 13 },
  { month: "Apr", found: 21, returned: 30 },
  { month: "May", found: 18, returned: 18 },
  { month: "Jun", found: 30, returned: 25 },
  { month: "Jul", found: 28, returned: 24 },
  { month: "Aug", found: 24, returned: 21 },
  { month: "Sep", found: 26, returned: 18 },
  { month: "Oct", found: 21, returned: 19 },
  { month: "Nov", found: 29, returned: 23 },
  { month: "Dec", found: 19, returned: 20 },
];

export { users, discs, trends };
