import type { Disc, User, Template } from "./definitions";

type UserSeed = Omit<User, "created_at" | "updated_at">;
type TemplateSeed = Omit<Template, "id" | "created_at" | "updated_at">;
type DiscSeed = Omit<Disc, "id" | "laf" | "created_at" | "updated_at">;

const users: UserSeed[] = [
  {
    id: "35074acb-9121-4e31-9277-4db3241ef591",
    name: "Jesse",
    laf: "Haple Mill Disc Golf",
    email: "jesse@fakedomain.com",
    password: "123456",
  },
  {
    id: "35074acb-9121-4e31-9277-4db3241ef593",
    name: "Alexia",
    laf: "Meadowstream Farms Disc Golf",
    email: "alexia@fakedomain.com",
    password: "123456",
  },
];

const templates: TemplateSeed[] = [
  {
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    name: "Jesse's Notification Template",
    type: "notification",
    content: `Hi, $name! Your $color $brand $plastic $mold has been found at $laf.
      Please pick it up during regular business hours.
      Your disc will be held until $held_until.`,
    is_default: true,
  },
  {
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    name: "Jesse's Reminder Template",
    type: "reminder",
    content: `Hi, $name! Your $color $brand $plastic $mold is still at $laf.
      Please pick it up during regular business hours.
      Your disc will be held until $held_until.`,
    is_default: true,
  },
  {
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    name: "Jesse's Extension Template",
    type: "extension",
    content: `Hi, $name! The pick-up date for your $color $brand $plastic $mold has been extended.
      $laf will now hold your disc until $held_until.
      Please pick it up during regular business hours.`,
    is_default: true,
  },
];

const discs: DiscSeed[] = [
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked up",
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked up",
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef591",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef593",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked up",
    user_id: "35074acb-9121-4e31-9277-4db3241ef593",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef593",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef593",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef593",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked up",
    user_id: "35074acb-9121-4e31-9277-4db3241ef593",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef593",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting pickup",
    user_id: "35074acb-9121-4e31-9277-4db3241ef593",
    notification_template: null,
    notification_text: "seed",
    reminder_template: null,
    reminder_text: "seed",
    extension_template: null,
    extension_text: "seed",
    held_until: null,
  },
];

const trends = [
  { month: "Jan", found: 20, returned: 18 },
  { month: "Feb", found: 21, returned: 20 },
  { month: "Mar", found: 22, returned: 13 },
  { month: "Apr", found: 21, returned: 30 },
  { month: "May", found: 18, returned: 18 },
  { month: "Jun", found: 30, returned: 25 },
  { month: "Jul", found: 28, returned: 24 },
  { month: "Aug", found: 24, returned: 21 },
  { month: "Sep", found: 26, returned: 18 },
  { month: "Oct", found: 21, returned: 19 },
  { month: "Nov", found: 29, returned: 23 },
  { month: "Dec", found: 19, returned: 20 },
];

export { users, templates, discs, trends };
