import { InsertUser } from "./schema/users";
import { InsertTemplate } from "./schema/templates";
import { InsertDisc } from "./schema/discs";
import { InsertTrend } from "./schema/trends";

export const seedUsers: InsertUser[] = [
  {
    id: "35074acb-9121-4e31-9277-4db3241ef591",
    name: "Jesse",
    laf: "Haple Mill Disc Golf",
    email: "jesse@fakedomain.com",
  },
  {
    id: "35074acb-9121-4e31-9277-4db3241ef593",
    name: "Alexia",
    laf: "Meadowstream Farms Disc Golf",
    email: "alexia@fakedomain.com",
  },
];

export const seedTemplates: InsertTemplate[] = [
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    name: "Jesse's Notification Template",
    type: "initial",
    content: `Hi, $name! Your $color $brand $plastic $mold has been found at $laf. Please pick it up during regular business hours. Your disc will be held until $heldUntil.`,
    isDefault: true,
  },
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    name: "Jesse's Reminder Template",
    type: "reminder",
    content: `Hi, $name! Your $color $brand $plastic $mold is still at $laf. Please pick it up during regular business hours. Your disc will be held until $heldUntil.`,
    isDefault: true,
  },
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    name: "Jesse's Extension Template",
    type: "extension",
    content: `Hi, $name! The pick-up date for your $color $brand $plastic $mold has been extended. $laf will now hold your disc until $heldUntil. Please pick it up during regular business hours.`,
    isDefault: true,
  },
];

export const seedDiscs: InsertDisc[] = [
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked_up",
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked_up",
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef593",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked_up",
    userId: "35074acb-9121-4e31-9277-4db3241ef593",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef593",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef593",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "blue",
    brand: "Innova",
    plastic: "Star",
    mold: "Destroyer",
    location: "Shelf 1",
    notes: "Jesse's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef593",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "JS",
    phone: "1111111111",
    color: "red",
    brand: "MVP",
    plastic: "Fission",
    mold: "Wave",
    location: "Shelf 1",
    notes: "",
    notified: false,
    reminded: false,
    status: "picked_up",
    userId: "35074acb-9121-4e31-9277-4db3241ef593",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "yellow",
    brand: "Westside",
    plastic: "VIP",
    mold: "Bard",
    location: "Shelf 2",
    notes: "",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef593",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
  {
    name: "AC",
    phone: "2222222222",
    color: "pink",
    brand: "Innova",
    plastic: "Champion",
    mold: "Teebird",
    location: "Shelf 2",
    notes: "Alexia's favorite disc",
    notified: false,
    reminded: false,
    status: "awaiting_pickup",
    userId: "35074acb-9121-4e31-9277-4db3241ef593",
    initialText: "seed",
    reminderText: "seed",
    extensionText: "seed",
    heldUntil: null,
  },
];

export const seedTrends: InsertTrend[] = [
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    month: "January",
    year: 2024,
    found: 20,
    returned: 18,
  },
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    month: "February",
    year: 2024,
    found: 24,
    returned: 22,
  },
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    month: "March",
    year: 2024,
    found: 30,
    returned: 28,
  },
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    month: "April",
    year: 2024,
    found: 20,
    returned: 18,
  },
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    month: "May",
    year: 2024,
    found: 24,
    returned: 22,
  },
  {
    userId: "35074acb-9121-4e31-9277-4db3241ef591",
    month: "June",
    year: 2024,
    found: 30,
    returned: 28,
  },
];
